### ISSUE TITLE
uninitialized memory can be dropped on panic: 'misc::vec_with_size()'

### ISSUE THREAD

**Issue by JOE1994** [Yoric/telemetry.rs#45]
Hello,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description

https://github.com/Yoric/telemetry.rs/blob/5c810a8345be7d763ab1c4a716683188e36aceb4/src/misc.rs#L138-L151

User provided `T::clone()` can potentially panic, and if `T::clone()` panics while `vec` is (partially) uninitialized, **uninitialized memory (uninitialized `T`) is dropped** and can lead to undefined behavior.

Thank you for checking out this issue :)

**Comment by Shnatsel** [comment]
Heads up: this issue has been included in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on.

Once a fix is released to crates.io, please open a pull request to update the advisory with the patched version, or file an issue on [the advisory database repository](https://github.com/RustSec/advisory-db).
